# Generated by Django 5.2.6 on 2025-10-09 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '分析待ち'), ('processing', '分析中'), ('completed', '完了'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='分析ステータス')),
                ('total_proposals', models.PositiveIntegerField(default=0, verbose_name='総提案数')),
                ('unique_proposers', models.PositiveIntegerField(default=0, verbose_name='提案者数')),
                ('common_themes', models.JSONField(default=list, verbose_name='共通テーマ')),
                ('innovative_solutions', models.JSONField(default=list, verbose_name='革新的解決案')),
                ('feasibility_analysis', models.JSONField(default=dict, verbose_name='実現可能性分析')),
                ('executive_summary', models.TextField(blank=True, verbose_name='エグゼクティブサマリー')),
                ('detailed_analysis', models.TextField(blank=True, verbose_name='詳細分析')),
                ('recommendations', models.TextField(blank=True, verbose_name='推奨事項')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='分析完了日時')),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='challenges.challenge', verbose_name='課題')),
            ],
            options={
                'verbose_name': '課題分析',
                'verbose_name_plural': '課題分析一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.PositiveIntegerField(verbose_name='提案ID')),
                ('innovation_score', models.FloatField(default=0.0, verbose_name='革新性スコア')),
                ('feasibility_score', models.FloatField(default=0.0, verbose_name='実現可能性スコア')),
                ('impact_score', models.FloatField(default=0.0, verbose_name='影響度スコア')),
                ('key_themes', models.JSONField(default=list, verbose_name='主要テーマ')),
                ('strengths', models.JSONField(default=list, verbose_name='強み')),
                ('concerns', models.JSONField(default=list, verbose_name='懸念点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='challenge_analytics.challengeanalysis', verbose_name='分析')),
            ],
            options={
                'verbose_name': '提案洞察',
                'verbose_name_plural': '提案洞察一覧',
                'ordering': ['-innovation_score', '-feasibility_score'],
                'unique_together': {('analysis', 'proposal_id')},
            },
        ),
    ]
