# Generated by Django 5.2.6 on 2025-10-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalinsight',
            name='insightfulness_score',
            field=models.FloatField(default=0.5, verbose_name='支持率スコア'),
        ),
        migrations.AlterField(
            model_name='proposalinsight',
            name='feasibility_score',
            field=models.FloatField(default=0.0, verbose_name='実現可能性スコア（非推奨）'),
        ),
    ]
