# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_analytics', '0002_proposalinsight_insightfulness_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalinsight',
            name='proposal_char_count',
            field=models.PositiveIntegerField(default=0, verbose_name='解決案文字数（タイブレーク用）'),
        ),
    ]
