# Generated by Django 5.2.6 on 2026-02-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_analytics', '0003_proposalinsight_proposal_char_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeanalysis',
            name='recommendations_source',
            field=models.CharField(blank=True, max_length=20, verbose_name='総括生成元'),
        ),
    ]
