# Generated by Django 5.2.6 on 2025-10-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposerprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='proposerprofile',
            name='expertise',
        ),
        migrations.AddField(
            model_name='contributorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所在地'),
        ),
        migrations.AddField(
            model_name='proposerprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='国籍'),
        ),
    ]
