# Generated by Django 5.2.6 on 2026-04-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_contributorprofile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposerprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='proposerprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='proposerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='proposerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='proposerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性'), ('other', 'その他')], max_length=10, null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='proposerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号'),
        ),
    ]
