# Generated by Django 5.2.6 on 2026-04-25 10:46

from django.db import migrations, models
from django.db.models import Q
from django.db.models.functions import Lower


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_email_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(
                Lower('email'),
                condition=Q(user_type__in=['contributor', 'proposer']),
                name='uniq_lower_email_app_users_only',
            ),
        ),
    ]
