# Generated by Django 5.2.6 on 2025-09-27 07:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='基準名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('criteria_type', models.CharField(choices=[('random', 'ランダム'), ('rating', '評価基準'), ('experience', '経験値'), ('location', '地域'), ('availability', '利用可能時間'), ('custom', 'カスタム')], max_length=50, verbose_name='基準タイプ')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='パラメータ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '選出基準',
                'verbose_name_plural': '選出基準',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='選出人数')),
                ('selected_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='実際の選出人数')),
                ('status', models.CharField(choices=[('pending', '選出中'), ('completed', '選出完了'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('selection_method', models.CharField(default='random', max_length=50, verbose_name='選出方法')),
                ('selection_criteria', models.JSONField(blank=True, default=dict, verbose_name='選出基準')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='通知送信済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='challenges.challenge', verbose_name='課題')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_selections', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('selected_users', models.ManyToManyField(blank=True, related_name='selections', to=settings.AUTH_USER_MODEL, verbose_name='選出されたユーザー')),
            ],
            options={
                'verbose_name': '選出',
                'verbose_name_plural': '選出',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('selected', '選出'), ('removed', '除外'), ('replaced', '代替')], max_length=50, verbose_name='アクション')),
                ('reason', models.TextField(blank=True, verbose_name='理由')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='メタデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='selections.selection', verbose_name='選出')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_history', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '選出履歴',
                'verbose_name_plural': '選出履歴',
                'ordering': ['-created_at'],
            },
        ),
    ]
