# Generated by Django 5.2.6 on 2025-10-07 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        ('proposals', '0006_proposalcomment_is_read'),
        ('selections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeUserAnonymousName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('anonymous_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposals.anonymousname', verbose_name='匿名名')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_anonymous_names', to='challenges.challenge', verbose_name='課題')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_anonymous_names', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '課題ユーザー匿名名',
                'verbose_name_plural': '課題ユーザー匿名名',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['challenge', 'user'], name='selections__challen_271a74_idx')],
                'unique_together': {('challenge', 'user')},
            },
        ),
    ]
