# Generated by Django 5.2.6 on 2025-10-19 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_populate_phase_deadlines'),
        ('selections', '0002_challengeuseranonymousname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvaluationCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_completed_all_evaluations', models.BooleanField(default=False, verbose_name='全評価完了')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_evaluation_completions', to='challenges.challenge', verbose_name='課題')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_completions', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザー評価完了状態',
                'verbose_name_plural': 'ユーザー評価完了状態',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['challenge', 'user'], name='selections__challen_087cfe_idx'), models.Index(fields=['challenge', 'has_completed_all_evaluations'], name='selections__challen_ea6767_idx')],
                'unique_together': {('challenge', 'user')},
            },
        ),
    ]
