# Generated by Django 5.2.6 on 2026-04-15 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0003_userevaluationcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='required_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(790)], verbose_name='選出人数'),
        ),
    ]
