# Generated by Django 5.2.6 on 2025-09-26 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion', models.TextField(verbose_name='結論')),
                ('reasoning', models.TextField(verbose_name='理由')),
                ('is_adopted', models.BooleanField(default=False, verbose_name='採用フラグ')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='challenges.challenge', verbose_name='課題')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL, verbose_name='提案者')),
            ],
            options={
                'verbose_name': '提案',
                'verbose_name_plural': '提案一覧',
                'ordering': ['-created_at'],
                'unique_together': {('challenge', 'proposer')},
            },
        ),
        migrations.CreateModel(
            name='ProposalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_section', models.CharField(choices=[('reasoning', '理由'), ('inference', '推論過程')], max_length=20, verbose_name='コメント対象')),
                ('conclusion', models.TextField(verbose_name='コメントの結論')),
                ('reasoning', models.TextField(verbose_name='コメントの理由')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_comments', to=settings.AUTH_USER_MODEL, verbose_name='コメント投稿者')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='proposals.proposal', verbose_name='提案')),
            ],
            options={
                'verbose_name': '提案コメント',
                'verbose_name_plural': '提案コメント一覧',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.CharField(choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], max_length=10, verbose_name='評価')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='評価者')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='proposals.proposal', verbose_name='提案')),
            ],
            options={
                'verbose_name': '提案評価',
                'verbose_name_plural': '提案評価一覧',
                'ordering': ['-created_at'],
                'unique_together': {('proposal', 'evaluator')},
            },
        ),
    ]
