# Generated by Django 5.2.6 on 2025-09-28 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('animal', 'Animal'), ('plant', 'Plant'), ('inorganic', 'Inorganic')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anonymous Name',
                'verbose_name_plural': 'Anonymous Names',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='proposalevaluation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='proposalevaluation',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='proposalevaluation',
            name='proposal',
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Proposal', 'verbose_name_plural': 'Proposals'},
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='proposal',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='solution_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('adopted', 'Adopted'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='proposal',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='challenges.challenge'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='is_adopted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='anonymous_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposals.anonymousname'),
        ),
        migrations.DeleteModel(
            name='ProposalComment',
        ),
        migrations.DeleteModel(
            name='ProposalEvaluation',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='reasoning',
        ),
    ]
