# Generated by Django 5.2.6 on 2025-09-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_anonymousname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='title',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='solution_details',
        ),
        migrations.AddField(
            model_name='proposal',
            name='conclusion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='reasoning',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
