# Generated by Django 5.2.6 on 2025-09-30 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_auto_20250928_2353'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='conclusion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='reasoning',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='ProposalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_section', models.CharField(choices=[('reasoning', '理由'), ('inference', '推論過程')], max_length=20, verbose_name='コメント対象')),
                ('conclusion', models.TextField(verbose_name='コメントの結論')),
                ('reasoning', models.TextField(verbose_name='コメントの理由')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_comments', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='proposals.proposal')),
            ],
            options={
                'verbose_name': 'Proposal Comment',
                'verbose_name_plural': 'Proposal Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalCommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='返信内容')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='proposals.proposalcomment')),
                ('replier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_comment_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposal Comment Reply',
                'verbose_name_plural': 'Proposal Comment Replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.CharField(choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], max_length=10, verbose_name='評価')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_evaluations', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='proposals.proposal')),
            ],
            options={
                'verbose_name': 'Proposal Evaluation',
                'verbose_name_plural': 'Proposal Evaluations',
                'unique_together': {('proposal', 'evaluator')},
            },
        ),
        migrations.CreateModel(
            name='ProposalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='参考メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='proposals.proposal')),
                ('referencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_references', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposal Reference',
                'verbose_name_plural': 'Proposal References',
                'unique_together': {('proposal', 'referencer')},
            },
        ),
    ]
