# Generated by Django 5.2.6 on 2025-09-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_alter_proposal_conclusion_alter_proposal_reasoning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalevaluation',
            name='score',
            field=models.IntegerField(default=0, verbose_name='点数'),
        ),
    ]
