# Generated by Django 5.2.6 on 2025-10-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_proposalevaluation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalcomment',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='既読フラグ'),
        ),
    ]
