# Generated by Django 5.2.6 on 2025-10-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_proposalcomment_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalevaluation',
            name='insight_level',
            field=models.CharField(blank=True, choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=1, null=True, verbose_name='示唆性評価'),
        ),
        migrations.AddField(
            model_name='proposalevaluation',
            name='insight_score',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='示唆性点数'),
        ),
        migrations.AddField(
            model_name='proposalevaluation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='proposalevaluation',
            name='evaluation',
            field=models.CharField(choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], max_length=10, verbose_name='独創性評価'),
        ),
        migrations.AlterField(
            model_name='proposalevaluation',
            name='score',
            field=models.IntegerField(default=0, verbose_name='独創性点数'),
        ),
    ]
