# Generated by Django 5.2.6

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_proposalevaluation_insight_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalEditReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_references', to='proposals.proposalcomment')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_references', to='proposals.proposal')),
            ],
            options={
                'verbose_name': '解決案編集参考',
                'verbose_name_plural': '解決案編集参考',
                'unique_together': {('proposal', 'comment')},
            },
        ),
    ]
