# Generated by Django 5.2.6 on 2025-10-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_payment_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='メタデータ'),
        ),
    ]
