# Generated by Django 5.2.6 on 2025-10-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('proposal_reward', '提案報酬'), ('adoption_reward', '採用報酬'), ('deposit', '入金'), ('stripe_deposit', 'Stripe入金'), ('withdrawal', '出金')], max_length=20, verbose_name='支払い種別'),
        ),
    ]
