# Generated by Django 5.2.6 on 2025-10-06 10:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('spam', 'スパム'), ('harassment', 'ハラスメント'), ('inappropriate_content', '不適切なコンテンツ'), ('violence', '暴力的な内容'), ('hate_speech', 'ヘイトスピーチ'), ('copyright', '著作権侵害'), ('fake_news', 'フェイクニュース'), ('other', 'その他')], max_length=50, verbose_name='報告理由')),
                ('description', models.TextField(blank=True, verbose_name='詳細説明')),
                ('status', models.CharField(choices=[('pending', '審査待ち'), ('under_review', '審査中'), ('resolved', '解決済み'), ('dismissed', '却下')], default='pending', max_length=20, verbose_name='ステータス')),
                ('moderator_notes', models.TextField(blank=True, verbose_name='モデレーター備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='報告日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解決日時')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_moderated', to=settings.AUTH_USER_MODEL, verbose_name='担当モデレーター')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='報告者')),
            ],
            options={
                'verbose_name': '報告',
                'verbose_name_plural': '報告一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'スパム行為'), ('harassment', 'ハラスメント'), ('inappropriate_content', '不適切なコンテンツ'), ('violence', '暴力的な内容'), ('hate_speech', 'ヘイトスピーチ'), ('copyright', '著作権侵害'), ('fake_news', 'フェイクニュース'), ('multiple_violations', '複数回の違反'), ('other', 'その他')], max_length=50, verbose_name='停止理由')),
                ('description', models.TextField(verbose_name='停止理由詳細')),
                ('suspended_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='停止開始日時')),
                ('suspended_until', models.DateTimeField(verbose_name='停止終了日時')),
                ('status', models.CharField(choices=[('active', '停止中'), ('expired', '期限切れ'), ('lifted', '解除済み')], default='active', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('lifted_at', models.DateTimeField(blank=True, null=True, verbose_name='解除日時')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensions_given', to=settings.AUTH_USER_MODEL, verbose_name='実行モデレーター')),
                ('related_reports', models.ManyToManyField(blank=True, to='moderation.report', verbose_name='関連報告')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to=settings.AUTH_USER_MODEL, verbose_name='対象ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザー利用停止',
                'verbose_name_plural': 'ユーザー利用停止一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('report_created', '報告作成'), ('report_reviewed', '報告審査'), ('report_resolved', '報告解決'), ('user_suspended', 'ユーザー停止'), ('user_unsuspended', 'ユーザー停止解除'), ('content_hidden', 'コンテンツ非表示'), ('content_deleted', 'コンテンツ削除')], max_length=30, verbose_name='アクションタイプ')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(verbose_name='アクション詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='実行日時')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='実行者')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_against', to=settings.AUTH_USER_MODEL, verbose_name='対象ユーザー')),
            ],
            options={
                'verbose_name': 'モデレーションアクション',
                'verbose_name_plural': 'モデレーションアクション履歴',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type'], name='moderation__action__27908d_idx'), models.Index(fields=['created_at'], name='moderation__created_6378e6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'object_id'], name='moderation__content_408935_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='moderation__status_3fc7e7_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='moderation__created_7bb7e8_idx'),
        ),
        migrations.AddIndex(
            model_name='usersuspension',
            index=models.Index(fields=['user'], name='moderation__user_id_0bfe02_idx'),
        ),
        migrations.AddIndex(
            model_name='usersuspension',
            index=models.Index(fields=['status'], name='moderation__status_99eef7_idx'),
        ),
        migrations.AddIndex(
            model_name='usersuspension',
            index=models.Index(fields=['suspended_until'], name='moderation__suspend_409db0_idx'),
        ),
    ]
