# Generated by Django 5.2.6 on 2025-09-25 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='課題タイトル')),
                ('description', models.TextField(verbose_name='課題内容')),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='提案報酬')),
                ('adoption_reward', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='採用報酬')),
                ('required_participants', models.IntegerField(verbose_name='選出人数')),
                ('deadline', models.DateTimeField(verbose_name='期限')),
                ('status', models.CharField(choices=[('open', '募集中'), ('closed', '締切'), ('completed', '完了')], default='open', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributed_challenges', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name': '課題',
                'verbose_name_plural': '課題一覧',
                'ordering': ['-created_at'],
            },
        ),
    ]
