# Generated by Django 5.2.6 on 2025-10-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='edit_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='編集期限'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='evaluation_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='評価期限'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='proposal_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提案期限'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='deadline',
            field=models.DateTimeField(verbose_name='期限（全体）'),
        ),
    ]
