# Generated by Django 5.2.6 on 2025-10-19 01:43

from django.db import migrations
from datetime import timedelta

def populate_phase_deadlines(apps, schema_editor):
    """
    既存の課題に対して3つの期限を計算して設定
    既存のdeadlineから逆算して、created_atから3つの期限を計算
    """
    Challenge = apps.get_model('challenges', 'Challenge')
    
    for challenge in Challenge.objects.all():
        # 既に3つの期限が設定されている場合はスキップ
        if challenge.proposal_deadline and challenge.edit_deadline and challenge.evaluation_deadline:
            continue
        
        # 総期間（日数）を計算
        total_duration = challenge.deadline - challenge.created_at
        total_days = total_duration.days
        
        # 総日数が0以下の場合はスキップ
        if total_days <= 0:
            print(f"課題ID {challenge.id}: 期限が作成日以前のためスキップ")
            continue
        
        # 各期間の日数を計算（四捨五入）
        proposal_days = round(total_days * 0.4)
        edit_days = round(total_days * 0.4)
        evaluation_days = round(total_days * 0.2)
        
        # 合計の調整
        total_calculated = proposal_days + edit_days + evaluation_days
        if total_calculated != total_days:
            evaluation_days += (total_days - total_calculated)
        
        # 各期限を計算（23:59:59まで）
        proposal_deadline = challenge.created_at + timedelta(days=proposal_days)
        proposal_deadline = proposal_deadline.replace(hour=23, minute=59, second=59, microsecond=999999)
        
        edit_deadline = challenge.created_at + timedelta(days=proposal_days + edit_days)
        edit_deadline = edit_deadline.replace(hour=23, minute=59, second=59, microsecond=999999)
        
        evaluation_deadline = challenge.created_at + timedelta(days=proposal_days + edit_days + evaluation_days)
        evaluation_deadline = evaluation_deadline.replace(hour=23, minute=59, second=59, microsecond=999999)
        
        # 保存
        challenge.proposal_deadline = proposal_deadline
        challenge.edit_deadline = edit_deadline
        challenge.evaluation_deadline = evaluation_deadline
        challenge.save(update_fields=['proposal_deadline', 'edit_deadline', 'evaluation_deadline'])
        
        print(f"課題ID {challenge.id}: 提案={proposal_days}日, 編集={edit_days}日, 評価={evaluation_days}日")

def reverse_populate(apps, schema_editor):
    """ロールバック時は3つの期限をNullに戻す"""
    Challenge = apps.get_model('challenges', 'Challenge')
    Challenge.objects.all().update(
        proposal_deadline=None,
        edit_deadline=None,
        evaluation_deadline=None
    )

class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_edit_deadline_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_phase_deadlines, reverse_populate),
    ]
