# Generated by Django 5.2.6 on 2026-04-29 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(unique=True, verbose_name='Endpoint')),
                ('p256dh', models.TextField(verbose_name='公開鍵(p256dh)')),
                ('auth', models.TextField(verbose_name='認証鍵(auth)')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'Push購読',
                'verbose_name_plural': 'Push購読',
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_1159a5_idx')],
            },
        ),
    ]
